app:
  datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/recipemanagerdb
      username: postgres
      password: password
      pool-size: 30
spring:  
  jpa:  
    hibernate:  
      ddl-auto: none  
    database-platform: org.hibernate.dialect.PostgreSQLDialect      
jwt-expire: 900000